# Numpy Temel Array Yapıları

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
a = np.array([1,2,3])
type(a)

numpy.ndarray

In [4]:
np.array([3.14, 4, 5, 2.24])

array([3.14, 4.  , 5.  , 2.24])

In [5]:
np.array([3.14, 4, 5, 2.24], dtype=int)

array([3, 4, 5, 2])

In [6]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [7]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [11]:
np.full((3,5), -5)

array([[-5, -5, -5, -5, -5],
       [-5, -5, -5, -5, -5],
       [-5, -5, -5, -5, -5]])

In [12]:
np.arange(0,50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [13]:
np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [14]:
np.arange(0,50,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [15]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [17]:
np.random.normal(10,4)

12.307219455573259

In [18]:
np.random.normal(10,4, (4,2))

array([[ 2.17264151, 18.81521265],
       [ 3.47127085, 10.88513828],
       [ 8.6708797 ,  6.30007823],
       [ 7.98736149, 12.75287277]])

In [23]:
np.random.randint(0,10,(3,3))

array([[3, 5, 8],
       [0, 5, 5],
       [1, 9, 2]])

In [25]:
a = np.random.randint(10, size=5)
a

array([2, 7, 3, 3, 6])

In [26]:
a.ndim

1

In [27]:
a.shape

(5,)

In [28]:
a.dtype

dtype('int32')

In [31]:
b = np.random.randint(10, size = (3,5))

In [32]:
b

array([[9, 9, 8, 5, 7],
       [9, 5, 3, 9, 6],
       [7, 9, 4, 1, 1]])

In [33]:
b.ndim

2

In [34]:
b.shape

(3, 5)

In [35]:
b.size

15