In [1]:
import numpy as np

# Dizilerle İşlemler

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)


[5 7 9]


In [3]:
print(a-b)

[-3 -3 -3]


In [4]:
print(a**2)

[1 4 9]


In [6]:
print(a<2)

[ True False False]


In [7]:
x = np.array([ [1,2,3],[4,5,6] ])
y = np.array([ [1,2,3],[4,5,6] ])

print(x*y)

[[ 1  4  9]
 [16 25 36]]


In [9]:
z = y.T
z

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
matris = x.dot(z)
matris

array([[14, 32],
       [32, 77]])

In [11]:
t1 = np.array([[1,2,3],[4,5,6]])
print(t1.sum())

21


In [12]:
print(t1.sum(axis=1))

[ 6 15]


In [13]:
print(t1.sum(axis=0))

[5 7 9]


In [14]:
print(t1.max())

6


In [16]:
print(t1.max(axis=1))

[3 6]


In [17]:
f = np.array([ [1,2,3],[4,5,6] ])
print(np.sqrt(f))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [18]:
print(np.square(f))

[[ 1  4  9]
 [16 25 36]]


# Index and Slice

In [19]:
dizi = np.array([1,2,3,4,5,6,7,8,9])
print(dizi[0:4])

[1 2 3 4]


In [20]:
dizi[-1]

9

In [21]:
dizi[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [22]:
dizi2D = np.array([
    [1,2,3,4,5],[6,7,8,9,10]
])
dizi2D[1,1]

7

In [23]:
dizi2D[:,1]

array([2, 7])

In [24]:
dizi2D[1,1:4]

array([7, 8, 9])

In [25]:
dizi2D[-1,:]

array([ 6,  7,  8,  9, 10])

# Şekil Manüpilasyonu

In [26]:
dizi3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
vektor = dizi3.ravel()
vektor

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
vektor.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
d1= np.array([[1,2],[3,4]])
d2= np.array([[-1,-2],[-3,-4]])

dikey = np.vstack((d1,d2))
dikey

array([[ 1,  2],
       [ 3,  4],
       [-1, -2],
       [-3, -4]])

In [31]:
yatay = np.hstack((d1,d2))
yatay

array([[ 1,  2, -1, -2],
       [ 3,  4, -3, -4]])